

server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  jackson:
    serialization:
      fail-on-empty-beans: false
    date-format: yyyy-MM-dd


#Configurazione per i social(facebook per ora)
security:
  oauth2:
    client:
      client-id: 372321790055906
      client-secret: 78430eeee2421e47c72e60145abf7bdb
      access-token-uri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      token-name: oauth_token
      authentication-scheme: query
      client-authentication-scheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me


